### ISSUE TITLE
systemd state: started vs started: yes

### ISSUE THREAD

**Issue by jokjr** [semaphor-dk/dansabel#10]
```
- name: start something
  systemd:
    name: myservice
    started: True
```
is wrong, should be `state: started`.
I've made this typo a number of times because the other directives are boolean, and it would be nice to catch this.
