### ISSUE TITLE
with_* vs *:

### ISSUE THREAD

**Issue by jokjr** [semaphor-dk/dansabel#11]
```
- name: make some directories
  file:
    type: directory
    dest: "/tmp/directory_{{ item }}"
  items:
    - a
    - b
```
will throw an error:
```
ERROR! conflicting action statements: file, items                                                                             
```

because it should be `with_items:`. It seems like a plausible typo and should be easy to detect that there's more than one key under a `name:` when the second key isn't one of the finite set of additional allowed toplevel keys {`with_items`, `register`, `when`, etc}.
