### ISSUE TITLE
Warn when register: is idented incorrectly

### ISSUE THREAD

**Issue by jokjr** [semaphor-dk/dansabel#2]
For example:
```yaml
- name: copy template
  template:
    src: /foo
    dest: /bar/
    register: did_copy
```
instead of
```yaml
- name: copy template
  template:
    src: /foo
    dest: /bar/
  register: did_copy
```
