### ISSUE TITLE
Handle YAML references

### ISSUE THREAD

**Issue by jokjr** [semaphor-dk/dansabel#6]
[what is YAML references / anchors](https://blog.daemonl.com/2016/02/yaml.html)

```yaml
---
foo: &anchor
  K1: "One"
  K2: "Two"
  <<: &anchor4
    K4: "Four"

bar:
  <<: *anchor
  K2: "I Changed"
  K3: "Three"

kilroy: *anchor4
```
```json
{
    "foo": {
        "K1": "One",
        "K2": "Two",
        "K4": "Four"
    },
    "bar": {
        "K1": "One",
        "K2": "I Changed",
        "K3": "Three",
        "K4": "Four",
    },
    "kilroy": {
        "K4": "Four"
    }
}
```

We should be careful to handle cyclic references sensibly.
